# remotes:
#   - git_url: https://github.com/Lifeforce-Digital/.github
#     configs:
#       - .lefthook.yml

# Build commit messages
prepare-commit-msg:
  # parallel: false
  jobs:
    - name: commitizen-windows
      only:
        - run: powershell -Command "if ( ('$IsWindows' -eq 'True') -and (Test-Path '.git/COMMIT_EDITMSG') ) { exit 0 } else { exit 1 }"
      interactive: true
      run: pnpm cz --hook
      env:
        LEFTHOOK: "0"
    - name: commitizen-nix
      only:
        - run: uname
      interactive: true
      run: |
        COMMIT_MSG=$(cat {1} | sed -e 's/#.*//' -e '/^$/d')
        if [ -n "$COMMIT_MSG" ]; then
          exit 0
        fi
        pnpm cz --hook
      env:
        LEFTHOOK: "0"

# Validate commit messages
commit-msg:
  jobs:
    - name: commitlint
      run: pnpm commitlint --verbose --edit {1}

# Auto add fixed files to commit
pre-commit:
  jobs:
    - name: biome
      # run: pnpx @biomejs/biome check --write --no-errors-on-unmatched --files-ignore-unknown=true --colors=off {staged_files}
      run: pnpm biome:write --colors=off {staged_files}
      stage_fixed: true
    - name: prettier # Used for file types not supported by Biome
      run: pnpm prettier --write {staged_files}
      stage_fixed: true
