name: "\U0001F917 Task"
description: Anything that doesn't fit as a bug or feature, is a task e.g. R&D, documentation, code cleanup, deps, etc.
labels:
  - task
type: Task
body:
  - type: textarea
    id: task-description
    attributes:
      label: Describe the task
      description: |
        Specify why, what, who, where, when as needed to provide the overall task details.
      value: |
        ### Why:

        ### What:

        ### Who:

        ### Where:

        ### When:
    validations:
      required: true
  - type: textarea
    id: action-steps
    attributes:
      label: Action Steps
      description: Itemise the steps required to complete this task.
      value: |
        - [ ] e.g. Create docker compose for xyz
        - [ ] e.g. Set up VPS
        - [ ] e.g. Implement security so that only specified clients can make API calls
    validations:
      required: true
