name: Prefix issue ID
on:
  issues:
    types: [opened]

jobs:
  prefix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const issueNumber = context.issue.number;
            const repoName = context.repo.repo;
            const currentTitle = context.payload.issue.title;

            if (!currentTitle.startsWith("LD-${repoName}")) {
              const newTitle = `LD-${repoName}-${issueNumber}: ${currentTitle}`;
              await github.rest.issues.update({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: newTitle,
              });
            }
