name: Auto Assign Issue
on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const issueNumber = context.issue.number;
            const repoName = context.repo.repo;
            const assignees = ['PrimeDominus']; // Add GitHub usernames of assignees here
            await github.rest.issues.addAssignees({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: repoName,
              assignees: assignees,
            });
